<a href="https://colab.research.google.com/github/fedjkeee/Homework/blob/main/Copy_of_Part_1_HW_Write_our_own_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Домашнее задание. Часть 1.

- напишем свою собственную библиотеку

Вего за эту часть ДЗ можно набрать максимум **11.5 баллов**. Разбиение баллов по каждой из задач представлено непосредственно перед текстом каждой задачи.

**Дедлайн - пятница, 11.12.2020 в 23:59.**

Дедлайн жесткий, сдача после дедлайна - 0 баллов за ДЗ.

Ссылка на ноутбук в колабе: https://colab.research.google.com/drive/1LgWtESFmiNW1WlVFCHKyNl_BxAWxoL3Z?usp=sharing

Допустим мы хотим написать фнкцию, которая складывает 2 числа и сохранить ее в отдельный .py файл. Пример:

In [22]:
%%writefile lib.py
def summ(a1, b1):
    return a1+b1

Overwriting lib.py


In [23]:
from lib import summ

In [24]:
summ(2,6)

8

Попробуем запустить через "терминал"

In [25]:
!python3 lib.py

Ничего не происходит. А теперь добавим `if __name__ == "__main__"` в наш код и пересохраним файл lib.py

In [26]:
%%writefile lib.py
import sys

a1 = float( sys.argv[1] ) # Считываем аргументы прямо из терминала
b1 = float( sys.argv[2] ) # Считываем аргументы прямо из терминала

def summ(a1, b1):
    return a1+b1

if __name__ == "__main__":
    print(summ(a1, b1))


Overwriting lib.py


In [27]:
!python3 lib.py 2 4

6.0


# **Задание 1**

Реализуйте следующие функции и сохраните их в библиотеку **my_math_lib.py** (пока без использования конструкции `if __name__ == "__main__"`)

**1 point** 
1. **def deg_to_rad()**. Напишите программу на Python для преобразования градусов в радианы.  *(Note: Радиан - это стандартная единица измерения угла, используемая во многих областях математики. Измерение угла в радианах численно равно длине соответствующей дуги единичного круга; один радиан чуть меньше 57,3 градуса)* **1 point**

**1 point** 
2. **def rad_to_def()**. Напишите программу Python для преобразования радианов в градусы.

**1.5 point** 
3. **def discriminant()**. Напишите программу на Python для вычисления значения дискриминанта (вспоминаем квадратные уравнения). Входные данные три числа: x, y, z (учтите что корни могут быть комлЕксными!)

**1.5 point** 
4. **def power_base_sum()**. Напишите программу на Python, чтобы вычислить сумму всех цифр основания в указанной степени.

Пример: power_base_sum(2, 100)

Выход: 115



**2 point** 
5. **def magic_square()**. Напишите программу на Python для вычисления [магического квадрата](https://ru.wikipedia.org/wiki/Магический_квадрат)

Note:

Магический, или волшебный квадрат — это квадратная таблица , заполненная числами таким образом, что сумма чисел в каждой строке, каждом столбце и на обеих диагоналях одинакова. Сумма чисел в каждой строке, столбце и на диагоналях, называется магической константой, M.

**1 point** 
6. **def mult_list()**. Напишите функцию Python для умножения всех чисел в массиве list(), (размер листа на входе произвольный)

**1 point** 
7. **def create_list()**. Напишите функцию Python для создания и вывода списка (при помощи print()), в котором значения представляют собой квадрат чисел от 1 до 30 (оба включительно).

### 1.   
def deg_to_rad(). Напишите программу на Python для преобразования градусов в радианы. (Note: Радиан - это стандартная единица измерения угла, используемая во многих областях математики. Измерение угла в радианах численно равно длине соответствующей дуги единичного круга; один радиан чуть меньше 57,3 градуса) 1 point

In [28]:
%%writefile  my_math_lib.py

from math import pi
def deg_to_rad(deg): #преобразование градусов в радианы
  return (deg * pi)/180

Overwriting my_math_lib.py


### 2
def rad_to_def(). Напишите программу Python для преобразования радианов в градусы.

In [29]:
%%writefile  -a my_math_lib.py

def rad_to_deg(rad): #преобразования радианов в градусы.
  return (180 * rad)/pi

Appending to my_math_lib.py


### 3
def discriminant(). Напишите программу на Python для вычисления значения дискриминанта (вспоминаем квадратные уравнения). Входные данные три числа: x, y, z (учтите что корни могут быть комлЕксными!)

In [30]:
%%writefile  -a my_math_lib.py

def discriminant(x,y,z):
  return y ** 2 - 4 * x * z

Appending to my_math_lib.py


### 4
def power_base_sum(). Напишите программу на Python, чтобы вычислить сумму всех цифр основания в указанной степени.
Пример: power_base_sum(2, 100)

Выход: 115

In [31]:
%%writefile  -a my_math_lib.py

def power_base_sum(x,y):
  return sum(int(digit) for digit in str(x ** y)) 

Appending to my_math_lib.py


### 5
def magic_square(). Напишите программу на Python для вычисления магического квадрата

In [32]:
%%writefile  -a my_math_lib.py

import numpy as np
# Используется сиамский алгоритм для построения магического квадрата размером N (N- нечетное)
# https://en.wikipedia.org/wiki/Siamese_method
#
# начиная с центрального квадрата первого ряда с цифрой 1 (или первым номером любой арифметической прогрессии), основное движение для заполнения квадратов идет по диагонали вверх и вправо ( ↗ ),
# шаг за шагом. Когда ход покидает квадрат, он переносится в последнюю строку или первый столбец соответственно. 
# Если встречается заполненный прямоугольник, вместо этого нужно перемещаться на один прямоугольник вертикально вниз ( ↓ ), а затем продолжать, как раньше.

def magic_square(n):

    assert (n % 2 == 1),"PLease use odd N"
    arr = np.zeros((n,n))
    x = 0
    y = int((n + 1) / 2 - 1)
    arr[x][y] = 1

    for i in range(2, n * n + 1):
        x_old = x
        y_old = y

        if x == 0:
            x = n - 1
        else:
            x -= 1

        if y == n - 1:
            y = 0
        else:
            y += 1

        while arr[x][y] != 0:
            if x == n - 1:
                x = 0
            else:
                x = x_old + 1
            y = y_old

        arr[x][y] = i

    for j in arr:
        print(j)


Appending to my_math_lib.py


### 6
def mult_list(). Напишите функцию Python для умножения всех чисел в массиве list(), (размер листа на входе произвольный)

In [33]:
%%writefile  -a my_math_lib.py

def mult_list(l):
  res = 1
  for i in l:
    res*=i
  return res

Appending to my_math_lib.py


### 7
**def create_list()**. Напишите функцию Python для создания и вывода списка (при помощи print()), в котором значения представляют собой квадрат чисел от 1 до 30 (оба включительно).

In [34]:
%%writefile  -a my_math_lib.py

def create_list():
  lst = [i*i for i in range(1,31)]
  for i in lst:
    print(i)


Appending to my_math_lib.py


# **Задание 2**
Импортируйте все методы из модуля my_math_lib.

 **0.25 point** 
 - при помощи функции **def discriminant()** посчитайте дискриминант следующего уравнения: 
 $x^{2}+3 x+4=0$

**0.25 point** 
 - постройте магический квадрат размера 5х5

In [35]:
from my_math_lib import *

In [36]:
discriminant(1,3,4)

-7

In [37]:
magic_square(5)

[17. 24.  1.  8. 15.]
[23.  5.  7. 14. 16.]
[ 4.  6. 13. 20. 22.]
[10. 12. 19. 21.  3.]
[11. 18. 25.  2.  9.]


# **Задание 3**

**2 point**
* Добавьте в вашу библиотеку конструкцию `if __name__ == "__main__"`, которая должна принимать одну из вышеперечисленных функций. 
* Важно! аргументы, подаваемые в функцию, должны подаваться напряму через терминал (как в примере)! Используйте для этого библиотеку `sys`

In [38]:
%%writefile  -a my_math_lib.py

import sys
a = int( sys.argv[1] ) # Считываем аргументы прямо из терминала
b = int( sys.argv[2] ) # Считываем аргументы прямо из терминала
c = int( sys.argv[3] ) # Считываем аргументы прямо из терминала
if __name__ == "__main__":
    print(discriminant(a, b, c))

Appending to my_math_lib.py


In [39]:
# Пример вызова функции - Вы можете вызвать любую другую
!python3 my_math_lib.py 3 4 5 # Например если в __main__ вы указали def discriminant()

-44
